### ISSUE TITLE
Cannot find module 'utils/token'

### ISSUE THREAD

**Issue by liugddx** [follow-my-heart/yapi-plugin-import-swagger-customize#1]
3|app    | Error: Cannot find module 'utils/token'
3|app    |     at Function.Module._resolveFilename (module.js:470:15)
3|app    |     at Function.Module._load (module.js:418:25)
3|app    |     at Module.require (module.js:498:17)
3|app    |     at require (internal/module.js:20:19)
3|app    |     at Object.<anonymous>

**Comment by follow-my-heart** [comment]
拉下官方最新版的yapi~
