### ISSUE TITLE
老哥，能否支持一下单个项目配置多个swagger地址呢？感谢

### ISSUE THREAD

**Issue by aaronuu** [follow-my-heart/yapi-plugin-import-swagger-customize#3]
首先非常感谢作者提供了一个非常好用的工具，我有个小小的请求，单个项目导入多个swagger，能不能后续支持一下呢？
非常感谢

**Comment by follow-my-heart** [comment]
好的我考虑一下

**Comment by follow-my-heart** [comment]
我考虑一下。不过，单个项目为什么要导入多个swagger。你的每个swagger地址。都是对应一个后端服务吖。为什么要导入多个呢

**Comment by tanshion** [comment]
希望可以支持一下单个项目配置多个swagger地址，因为需要选取多个后台的部分api提供给外部使用
